onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi

# move here instead of .npmrc
shamefullyHoist: true
strictPeerDependencies: false
